name: Export and Deploy Apigee Proxy

on:
  push:
    branches:
      - main

jobs:
  export_and_deploy_proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install httpie
      run: sudo apt-get update && sudo apt-get install -y httpie

    - name: Export Apigee Proxy
      run: |
        http GET "https://api.google.apigee.com/v1/organizations/caramel-limiter-412805/apis/krithika-demo-proxy/revisions/1?format=bundle" \
          --download -o exported-proxy.zip \
          --verify=no

    - name: Archive Exported Proxy
      uses: actions/upload-artifact@v2
      with:
        name: exported-proxy
        path: exported-proxy.zip

    - name: Deploy Apigee Proxy to Eval Environment
      run: |
        http --verbose POST "https://api.google.apigee.com/v1/organizations/caramel-limiter-412805/apis/krithika-demo-proxy/revisions/1/deployments?action=deploy&env=eval" \
        --verify=no
