name: Export and Deploy Apigee Proxy

on:
  push:
    branches:
      - main

jobs:
  export_and_deploy_proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install httpie
      run: sudo apt-get update && sudo apt-get install -y httpie

    - name: Export Apigee Proxy
      run: |
        http GET "https://apigee.google.com/platform/zebra-nonprod/proxies/Savanna-API-Apigee-FinOps/revisions/1?format=bundle" \
          --download -o exported-proxy.zip \
          --verify=no

